In [1]:
import pandas as pd 
from sklearn.linear_model import LinearRegression
import seaborn as sns

In [2]:
data= pd.read_csv("movies.csv")

In [3]:
data

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [4]:
data.isnull().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [5]:
data.interpolate(inplace=True)

C:\Users\bedir\AppData\Local\Temp\ipykernel_13036\3565517206.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  data.interpolate(inplace=True)

In [6]:
data.isnull().sum()

Rank                  0
Title                 0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime (Minutes)     0
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             0
dtype: int64

In [7]:
data

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.130,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.460,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.120,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.320,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.020,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,36.130,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.540,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.010,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,38.825,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.640,11.0

In [8]:
# x= Rating & votes   Y= Revenue (Millions)
# split  x_train y_train  x_test y_test     80 --> train 20-> test  or 70--> train 30-> test

In [9]:
y=data["Revenue (Millions)"]
y

0      333.130
1      126.460
2      138.120
3      270.320
4      325.020
        ...
995     36.130
996     17.540
997     58.010
998     38.825
999     19.640
Name: Revenue (Millions), Length: 1000, dtype: float64

In [10]:
x_train=data.loc[:700,["Rating","Votes"]]
x_test=data.loc[701:,["Rating","Votes"]]

In [11]:
y_train=data.loc[:700,["Revenue (Millions)"]]
y_test=data.loc[701:,["Revenue (Millions)"]]

In [12]:
y_test

     Revenue (Millions)
701             218.630
702              90.360
703              49.550
704              23.230
705              42.840
..                  ...
995              36.130
996              17.540
997              58.010
998              38.825
999              19.640

[299 rows x 1 columns]

In [13]:
model = LinearRegression()

In [14]:
model.fit(x_train,y_train)

LinearRegression()

In [15]:
#4) test model  y=a+bx
y_predict=model.predict(x_test) # y_test

In [16]:
y_predict

array([[195.01229645],
       [107.21161072],
       [ 66.16121576],
       [ 60.21697738],
       [ 45.73636416],
       [ 92.68050837],
       [ 32.86844546],
       [ 65.28314823],
       [ 42.95665706],
       [158.17985849],
       [ 13.96800184],
       [ 33.3188255 ],
       [ 31.16895908],
       [ 70.28613133],
       [ 80.35719762],
       [ 51.56760649],
       [ 70.44600514],
       [117.70570449],
       [115.73986382],
       [ 50.11636358],
       [ 52.97140922],
       [107.13067021],
       [ 66.50122414],
       [ 81.42509926],
       [109.98970677],
       [129.52075503],
       [118.7731386 ],
       [102.05059276],
       [ 51.95821065],
       [ 92.9991741 ],
       [ 92.14487411],
       [ 23.45071449],
       [147.68884692],
       [ 13.71562755],
       [102.84710746],
       [ 49.31834933],
       [ 83.43545444],
       [ 52.08702563],
       [ 99.18262061],
       [ 62.06075828],
       [ 32.0573717 ],
       [ 49.31036262],
       [ 99.44866875],
       [ 45.57843595],
       [ 89.21938958],
       [ 66.93084058],
       [ 47.27329071],
       [ 48.92560495],
       [ 74.36675056],
       [ 69.8238069 ],
       [ 63.4079906 ],
       [117.50999062],
       [ 88.80559207],
       [ 59.36022412],
       [ 81.39788174],
       [ 56.17540369],
       [ 28.98750953],
       [ 85.25516651],
       [108.00039985],
       [ 43.86831981],
       [ 68.99060991],
       [ 35.93077183],
       [ 83.73443845],
       [100.24860506],
       [ 34.8266672 ],
       [ 95.20983664],
       [159.86706594],
       [ 60.05065452],
       [ 55.06804371],
       [151.03121116],
       [ 69.43451737],
       [184.42667742],
       [ 76.90075546],
       [ 85.57355448],
       [ 75.28221445],
       [ 61.15758507],
       [ 68.09435331],
       [ 63.20382532],
       [ 28.02458883],
       [100.00096902],
       [ 54.39048995],
       [ 60.62451561],
       [ 31.15582617],
       [ 34.2250809 ],
       [127.69991121],
       [ 25.23801987],
       [ 70.87860889],
       [ 51.28678804],
       [161.26386205],
       [ 57.91735923],
       [ 67.19786395],
       [ 83.30531793],
       [  7.67820298],
       [ 74.28606146],
       [ 99.07452421],
       [ 46.48706636],
       [120.77559505],
       [ 63.76196236],
       [ 91.47977242],
       [ 74.99951692],
       [ 86.57741643],
       [ 87.95075115],
       [ 72.8911493 ],
       [102.73781768],
       [ 58.72362823],
       [110.77043579],
       [ 60.06418847],
       [ 26.78067653],
       [ 57.18710272],
       [ 33.78204202],
       [ 86.54399436],
       [ 75.19812524],
       [ 59.88736398],
       [ 58.74038428],
       [110.17211661],
       [ 54.7260281 ],
       [113.18122768],
       [ 83.64460736],
       [ 67.01898236],
       [ 28.02390313],
       [ 70.81012735],
       [107.31305166],
       [ 23.36900515],
       [ 45.74514323],
       [ 54.04887538],
       [ 68.82782016],
       [ 54.03623353],
       [ 66.24485406],
       [145.12960131],
       [ 77.69441099],
       [ 38.63055865],
       [ 37.41910982],
       [ 67.98766156],
       [111.8398536 ],
       [ 48.21261703],
       [ 13.77439981],
       [107.04548249],
       [ 77.35851477],
       [  6.26512527],
       [ 78.54813679],
       [ 38.03884992],
       [ 67.56712546],
       [ 52.94577436],
       [ 80.41301582],
       [112.66714247],
       [ 54.19792478],
       [ 33.52937821],
       [ 34.96044833],
       [ 36.29374567],
       [ 94.77415554],
       [ 53.01458557],
       [ 56.2986901 ],
       [ 92.72896879],
       [125.74511796],
       [ 45.67993852],
       [133.22551892],
       [ 31.37360853],
       [ 80.67348347],
       [ 78.76156044],
       [ 59.44098662],
       [ -4.38320708],
       [ 47.82833379],
       [ 54.84556324],
       [ 36.75453731],
       [ 52.23575713],
       [ 25.8084192 ],
       [ 30.55086815],
       [ 35.98898654],
       [118.17362603],
       [ 15.61401177],
       [123.74645576],
       [ 74.33107675],
       [ 61.2046526 ],
       [ 64.4707197 ],
       [ 99.22114873],
       [ 91.18679143],
       [ 72.01833259],
       [ 97.49454944],
       [ 99.98253543],
       [ 26.14658865],
       [ 55.97078263],
       [ 99.39805634],
       [ 84.28293758],
       [ 44.12380955],
       [100.82265592],
       [ 75.50306239],
       [ 59.8960149 ],
       [ 76.1846237 ],
       [106.93591494],
       [ 87.74968469],
       [ 74.46260129],
       [112.29222911],
       [ 85.76609126],
       [ 85.11120167],
       [ 80.71324309],
       [ 40.93391145],
       [ 36.9182074 ],
       [ 91.38966844],
       [ 79.24465332],
       [ 40.53151253],
       [ 89.61424094],
       [ 44.50454791],
       [ 87.67136573],
       [103.49565951],
       [ 36.99321627],
       [ 31.34216529],
       [117.87584026],
       [ 53.39143276],
       [ 94.56639551],
       [ 38.85811192],
       [ 66.40104795],
       [ 58.71091988],
       [ 40.79039752],
       [ 38.59226532],
       [ 18.13970028],
       [119.28507182],
       [ 33.79679085],
       [ 81.84934852],
       [ 92.8360117 ],
       [ 56.49910897],
       [ 45.70075199],
       [ 86.35037571],
       [ 45.44496096],
       [125.04428083],
       [127.93897944],
       [ 47.79900929],
       [ 44.79571146],
       [ 39.72795795],
       [ 59.06372663],
       [ 55.99954956],
       [ 57.47192385],
       [ 51.97607492],
       [ 35.36042237],
       [ 38.1218524 ],
       [ 77.18315171],
       [ 91.91301687],
       [ 47.76754944],
       [ 20.78267705],
       [111.94631746],
       [ 56.02610977],
       [128.81548092],
       [ 44.52063975],
       [ 60.18387323],
       [ 79.07780128],
       [ 48.679981  ],
       [ 50.29180004],
       [ 49.26040753],
       [119.60519208],
       [ 39.22720029],
       [ 38.47725719],
       [ 89.84193411],
       [ 94.42301458],
       [ 40.5754861 ],
       [ 93.69774774],
       [ 65.21544038],
       [ 84.99706211],
       [ 75.52970086],
       [ 62.31624316],
       [101.63874083],
       [ 55.42522093],
       [ 45.7596524 ],
       [ 57.9950444 ],
       [ 55.70256101],
       [ 23.30744021],
       [ 36.84381084],
       [ 27.63705024],
       [ 48.06413695],
       [ 88.10365644],
       [ 97.81488786],
       [ 76.04267581],
       [ 91.15588913],
       [ 64.82531552],
       [ 74.59885232],
       [ 16.09968607],
       [ 47.63707839],
       [ 47.59094797],
       [ 60.01900489],
       [ 25.05563841],
       [ 48.132597  ],
       [ 25.54375423],
       [ 63.1387155 ],
       [ 47.1491191 ],
       [ 70.37996997],
       [ 32.62191279],
       [ 78.7278537 ],
       [ 73.07306808],
       [ 46.41606991],
       [ 41.81568037],
       [ 35.58369519],
       [ 74.44619154],
       [ 28.93379343],
       [ 50.53555666],
       [ 91.6495619 ],
       [ 84.62299097],
       [ 46.16909119],
       [ 75.44367092],
       [ 61.30910924],
       [ 49.57329328],
       [ 57.91447167]])

In [17]:
print(model.coef_) #y= w0 + w1*x1 +w2*x2

[[-1.89616574e+01  3.51162454e-04]]

In [18]:
print(model.intercept_)

[154.04455077]

In [19]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [20]:
dt=sns.load_dataset("tips")

In [21]:
dt  # y--> total_bill  x--> tip & size

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]